---

- stat: path=/swap
  register: s

- shell: fallocate -l {{ ec2_swap_size }} /swap
  when: s.stat.exists == false

- file:
    path: /swap
    mode: '0600'

- shell: mkswap /swap
  when: s.stat.exists == false

- mount: 
    name: swap
    src: /swap
    fstype: swap
    opts: defaults
    passno: '0'
    dump: '0'
    state: present

- name: 不要パッケージ
  apt: name={{ item }} state=absent autoremove=yes autoclean=yes
  with_items:
    - snapd
    - mdadm
    - open-iscsi
    - lvm2
    - at
    - lxcfs
    - accountsservice
    - policykit-1
